---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= Listen Sie die nicht verwalteten Apps auf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Applikationen auflisten, die aktuell nicht vom Astra gemanagt werden. Sie können dies als Teil der Auswahl einer zu verwaltenden App tun.


NOTE: In diesem Workflow sind alle Astra-Anwendungen aufgeführt. Sie können sich die Ausgabe ansehen, um zu bestimmen, welche Apps nicht verwaltet werden, indem Sie die prüfen `managedState` Feld.



=== 1. Listen Sie die Anwendungen auf

Führen Sie den folgenden REST-API-Aufruf aus.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /Account/{AccountID}/Topology/v1/Apps 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Einschließlich | Abfrage | Nein | Wählen Sie optional die Werte aus, die in der Antwort zurückgegeben werden sollen. 
|===


===== Curl Beispiel: Gibt alle Daten für alle Apps zurück

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl Beispiel: Geben Sie den Namen, id und managedState für alle Apps zurück

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Beispiel für eine JSON-Ausgabe

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----