---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords:  
summary:  
---
= Weitere Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Auf weitere Ressourcen erhalten Sie Zugriff. Dort erhalten Sie weitere Informationen zu NetApp Cloud Services und Support sowie ZU allgemeinen REST- und Cloud-Konzepten.



== Astra

* https://["Astra Control Center 2108-Dokumentation"^]
+
Dokumentation für die Astra Control Center-Software beim Kunden vor Ort.

* https://["Dokumentation des Astra Control Service"^]
+
Dokumentation für die Astra Control Service-Software, die in der Public Cloud verfügbar ist.

* https://["Astra Trident-Dokumentation"^]
+
Dokumentation für den Astra Trident Open Source Storage Orchestrator von NetApp verwaltet.





== NetApp Cloud-Ressourcen

* https://["NetApp Cloud-Lösungen"^]
+
Zentraler Standort für NetApp Cloud Lösungen.

* https://["NetApp Cloud Central Konsole"^]
+
NetApp Cloud Central Service-Konsole mit Anmeldung.

* https://["NetApp Support"^]
+
Sie erhalten Zugriff auf Tools für die Fehlerbehebung, Dokumentation und technische Support-Unterstützung.





== REST-Konzepte und Cloud-Technologie

* PhD https://["Dissertation"^] Von Roy Fielding
+
In dieser Publikation wurde das MODELL DER REST-Anwendungsentwicklung eingeführt und etabliert.

* https://["Auth0"^]
+
Dies ist der Authentifizierungs- und Autorisierungsplattform-Service, der vom Astra-Service für den Webzugriff genutzt wird.

* https://["RFC-Editor"^]
+
Maßgebliche Quelle für Web- und Internet-Standards wird als Sammlung von eindeutig nummerierten RFC-Dokumenten gepflegt.


