---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords:  
summary:  
---
= Weitere Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Auf weitere Ressourcen erhalten Sie Zugriff. Dort erhalten Sie weitere Informationen zu NetApp Cloud Services und Support sowie ZU allgemeinen REST- und Cloud-Konzepten.



== Astra

* https://docs.netapp.com/us-en/astra-control-center-2108/["Astra Control Center 2108-Dokumentation"^]
+
Dokumentation für die Astra Control Center-Software beim Kunden vor Ort.

* https://docs.netapp.com/us-en/astra-control-service/["Dokumentation des Astra Control Service"^]
+
Dokumentation für die Astra Control Service-Software, die in der Public Cloud verfügbar ist.

* https://docs.netapp.com/us-en/trident/["Astra Trident-Dokumentation"^]
+
Dokumentation für den Astra Trident Open Source Storage Orchestrator von NetApp verwaltet.





== NetApp Cloud-Ressourcen

* https://cloud.netapp.com/["NetApp Cloud-Lösungen"^]
+
Zentraler Standort für NetApp Cloud Lösungen.

* https://services.cloud.netapp.com/redirect-to-login?startOnSignup=false["NetApp Cloud Central Konsole"^]
+
NetApp Cloud Central Service-Konsole mit Anmeldung.

* https://mysupport.netapp.com/["NetApp Support"^]
+
Sie erhalten Zugriff auf Tools für die Fehlerbehebung, Dokumentation und technische Support-Unterstützung.





== REST-Konzepte und Cloud-Technologie

* PhD https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["Dissertation"^] Von Roy Fielding
+
In dieser Publikation wurde das MODELL DER REST-Anwendungsentwicklung eingeführt und etabliert.

* https://auth0.com/["Auth0"^]
+
Dies ist der Authentifizierungs- und Autorisierungsplattform-Service, der vom Astra-Service für den Webzugriff genutzt wird.

* https://www.rfc-editor.org/["RFC-Editor"^]
+
Maßgebliche Quelle für Web- und Internet-Standards wird als Sammlung von eindeutig nummerierten RFC-Dokumenten gepflegt.


